language: java
jdk:
- oraclejdk8
script: mvn clean install jacoco:report coveralls:report
cache:
  directories:
  - node_modules
  
  before_install: 
  - chmod +x ./mvnw
  
  deploy:
  provider: heroku
  api_key:
    secure: "At/6EmGtpKjG/Ptm7JMZ4pwVYD4Qfla0RRAn7FFMQ34azP0Js2f5hVlh2H9M2i3gwSE7btpswpNy505qcOb/hEDlCqBX1haKIwJt+nUR/RaRKVHPqWn8keTCOYylGpZ8H2Hc2zRb7kk1WkwVkcoatxeHuc2ZcYJIZhdqAQNdJSk1TSEUk9qLoXbfG/4ajUnLI1GCzff7KT2D0WOSYSYIX3e+xrW6AAu8QThhIeS2/8zl5sKQriksiCUgf5x8yu4fLGab62T51zZVcddx9Ko/ox3ZBh5EFGLuX8D+3k+yVm1U1Hbg5xlL+m2kwwAdZh5eOucguVJ1O8m1QcNw2R0SLe5NnJ5utjWWuYcAUvbOL/4BVo14wJDr9Imnyn5mTUAxbVuWC73acTiykUlJvcMHRdo9g8vHoqCXPl4bnqMZOrBsJGjlLcPNIL/Sa0WvsUFXOpM7db+Bi5qSKHu46ZfabroixIEIj8B54wJNoQzLTQ5iGy66gjSxfZRKdMNL1d7JH5jIeCKQMUBAiMOdaGm2ZU201FLkUrIF8Piu6reQWOKKia4yGp3e8F8mNTWypZ2JSnHK9g2CC3RSaHjKUa1vXMfT8WAufZ8bxSCkoT75MPF9Zhtf9QeTr7ftlF9M8OUiu3V+t4TGooaINahcDrDTwzP2yY7ALY0XqC+enLGKK6I="
   app: onlus-app
  on:
    repo: prima-s/onlus-manager-test
