language: java

jdk:
- oraclejdk8
 
install: true
  
script: mvn clean install 

deploy:
  provider: heroku
  api_key:
    secure: "fefRJ/55OMh8+ALSUCks6lEYRwhK5nMXP4jaIufZjluZp6zi0J0HbxPvwh0z6LIeI/8YpkIpmtrDEE1DRdCeegcO9U3KdUZjr3W03wMr+Pgg4fr6Uw5JD8gJ4bNdlF8qi3vBfnXf2qK0IXMWpFn2rDWZcyiNblk/MguYaYA8Ig7SQHLAqz/xIBhsk0eJaKMREYnw6MVF2bDqDEZKC7hJgBmNYn2+6Nmszh5buz5SNjdU/2UEzi1zDrVtajFdQA+PxQi8zLOKc0mrwWn3VuL1RkDmjOkqdGbRlFwpt1LtvTpl/PtTwndTYeBc32Hc2sfwbHkoj8gfvtksLFRnLV7mq2IVGJ5F8wjBi+sS2sBCOf6LCGYIWDof8s4ncrcvy9+FuMQEYHALKRmVUKIOBedOZy6psey11bY9dSwDZEeJPpSH4eZl7H4zuzFA8ewpBoXKUahDsa2TM7DdCHsZ1H/rmCM5sKlwzDK+RSgPp207ibyo7SiEAQQP5HQ8n8dH10f3+spQe64wjjvZqcMhTg0/LkhUrSSynNXKBML2g3UGsN4E9hvwmUP07HsFlMXwH2GYoJEtFJPE0ouO+Ga8enWw8LaH6dXph5bd9akGas4pHpiwMuFXgcrZK3OrlDPKauwZJs+bMZXDV2R/XCa730uHpuXvA4uGCMI9KKcCPTjWLHU="
  

cache:
  directories:
  - node_modules
